package mx.sep.mec.web.ws.schemas;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-08T11:39:25.199-06:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://ws.web.mec.sep.mx/schemas", name = "TitulosPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TitulosPortType {

    @WebMethod
    @WebResult(name = "cancelaTituloElectronicoResponse", targetNamespace = "http://ws.web.mec.sep.mx/schemas", partName = "cancelaTituloElectronicoResponse")
    public CancelaTituloElectronicoResponse cancelaTituloElectronico(

        @WebParam(partName = "cancelaTituloElectronicoRequest", name = "cancelaTituloElectronicoRequest", targetNamespace = "http://ws.web.mec.sep.mx/schemas")
        CancelaTituloElectronicoRequest cancelaTituloElectronicoRequest
    );

    @WebMethod
    @Oneway
    public void cancelarTituloInstitucion(

        @WebParam(partName = "cancelarTituloInstitucionRequest", name = "cancelarTituloInstitucionRequest", targetNamespace = "http://ws.web.mec.sep.mx/schemas")
        CancelarTituloInstitucionRequest cancelarTituloInstitucionRequest
    );

    @WebMethod
    @WebResult(name = "descargaTituloElectronicoResponse", targetNamespace = "http://ws.web.mec.sep.mx/schemas", partName = "descargaTituloElectronicoResponse")
    public DescargaTituloElectronicoResponse descargaTituloElectronico(

        @WebParam(partName = "descargaTituloElectronicoRequest", name = "descargaTituloElectronicoRequest", targetNamespace = "http://ws.web.mec.sep.mx/schemas")
        DescargaTituloElectronicoRequest descargaTituloElectronicoRequest
    );

    @WebMethod
    @WebResult(name = "cargaTituloElectronicoResponse", targetNamespace = "http://ws.web.mec.sep.mx/schemas", partName = "cargaTituloElectronicoResponse")
    public CargaTituloElectronicoResponse cargaTituloElectronico(

        @WebParam(partName = "cargaTituloElectronicoRequest", name = "cargaTituloElectronicoRequest", targetNamespace = "http://ws.web.mec.sep.mx/schemas")
        CargaTituloElectronicoRequest cargaTituloElectronicoRequest
    );

    @WebMethod
    @WebResult(name = "consultaProcesoTituloElectronicoResponse", targetNamespace = "http://ws.web.mec.sep.mx/schemas", partName = "consultaProcesoTituloElectronicoResponse")
    public ConsultaProcesoTituloElectronicoResponse consultaProcesoTituloElectronico(

        @WebParam(partName = "consultaProcesoTituloElectronicoRequest", name = "consultaProcesoTituloElectronicoRequest", targetNamespace = "http://ws.web.mec.sep.mx/schemas")
        ConsultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest
    );
}
